export enum Roles { 
    SUPERADMIN = 'SUPERADMIN',
    ADMIN = 'ADMIN',
    EDITOR = 'EDITOR',
    USER = 'USER',
    PREMIUM_USER_SILVER = 'USER_SILVER',
    PREMIUM_USER_BRONZE = 'USER_BRONZE',
    PREMIUM_USER_GOLE = 'USER_GOLD',
 }